all:
	pandoc varunpatro_codeswitching.md transcript.md --smart --standalone \
		--bibliography varunpatro_codeswitching_citations.bib \
		-o varunpatro_codeswitching.pdf && open varunpatro_codeswitching.pdf
