all:
	pandoc varunpatro_relativitypaper.md --smart --standalone \
		--bibliography varunpatro_relativitypaper_citations.bib \
		-o varunpatro_relativitypaper.pdf && open varunpatro_relativitypaper.pdf
